# © 2017 Joseph Cameron - All Rights Reserved
# Project: Hello Travis CI
# Created on 2017-12-7.

dist: trusty
sudo: required
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      env: Code Coverage
      before_install: pip install --user cpp-coveralls
      script:
        - |
          cd workspace
          cmake ../src -DCMAKE_CXX_FLAGS="-g -O0 -Wall -fprofile-arcs -ftest-coverage"
          make
          make test
      after_success:
        - |
          cd ..
          coveralls --exclude tests

    - os: linux
      addons:
        apt:
          packages:
            - doxygen
      compiler: gcc
      env: Generate documentation
      script:
        - |
          cd docs
          ./generate-documents.sh
          mv html ~
          cd ..
          git remote set-url --push origin https://${GITHUB_PUBLIC_REPO_TOKEN}@$(git config --get remote.origin.url | sed -e "s/^https:\/\///")
          git fetch --all
          git checkout -b gh-pages;git pull origin gh-pages;git clean -fxd;git reset --hard
          cp -rf ~/html/* .
          git add --all;git reset build;git commit -m "Docs for ${CURRENT_COMMIT_HASH}"
          git pull origin gh-pages;git push --force --set-upstream origin gh-pages
          
    - os: linux
      compiler: gcc
      env: Build, Test & Deploy
      script:
        - |
          cd workspace
          cmake ../src -DCMAKE_CXX_FLAGS="-pedantic -Wall -Wextra -Ofast -flto -funroll-loops -m64 -march=native"
          make
          ctest --extra-verbose
      after_success:
        - |
          cd ..;touch build/${CURRENT_COMMIT_HASH};zip -r ~/${TRAVIS_OS_NAME}.zip build -x build/.keep
          git remote set-url --push origin https://${GITHUB_PUBLIC_REPO_TOKEN}@$(git config --get remote.origin.url | sed -e "s/^https:\/\///")
          git fetch --all
          git checkout -b gh-pages;git pull origin gh-pages;git clean -fxd;git reset --hard
          mv ~/${TRAVIS_OS_NAME}.zip ./build
          git add ./build/${TRAVIS_OS_NAME}.zip; git commit -m "${TRAVIS_OS_NAME} build for ${CURRENT_COMMIT_HASH}"
          git push --force --set-upstream origin gh-pages

    - os: osx
      compiler: clang
      env: Build, Test & Deploy
      script:
        - |
          cd workspace
          cmake ../src -DCMAKE_CXX_FLAGS="-pedantic -Weverything -Wno-c++98-compat -Ofast -flto -funroll-loops -m64 -march=native"
          make
          ctest --extra-verbose
      after_success:
        - |
          cd ..;touch build/${CURRENT_COMMIT_HASH};zip -r ~/${TRAVIS_OS_NAME}.zip build -x build/.keep
          git remote set-url --push origin https://${GITHUB_PUBLIC_REPO_TOKEN}@$(git config --get remote.origin.url | sed -e "s/^https:\/\///")
          git fetch --all
          git checkout -b gh-pages;git pull origin gh-pages;git clean -fxd;git reset --hard
          mv ~/${TRAVIS_OS_NAME}.zip ./build
          git add ./build/${TRAVIS_OS_NAME}.zip; git commit -m "${TRAVIS_OS_NAME} build for ${CURRENT_COMMIT_HASH}"
          git push --force --set-upstream origin gh-pages

before_script: 
  - |
    CURRENT_COMMIT_HASH="$(git rev-parse HEAD)"
 