# © 2017 Joseph Cameron - All Rights Reserved
# Project: Hello Travis CI
# Created on 2017-12-7.

dist: trusty
sudo: required
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      env: Code Coverage
      before_install: pip install --user cpp-coveralls
      script:
        - |
          cd workspace
          cmake ../src -DCMAKE_CXX_FLAGS="-g -O0 -Wall -fprofile-arcs -ftest-coverage"
          make
          make test
          cd ..
          coveralls --exclude tests

    - os: linux
      addons:
        apt:
          packages:
            - doxygen
      compiler: gcc
      env: Documentation generation
      script:
        - |
          cd docs
          ./generate-documents.sh
          CURRENT_COMMIT_HASH="$(git rev-parse HEAD)"
          mv html ~
          cd ..
          git fetch --all
          git checkout -b gh-pages
          git pull;git clean -fxd;git reset --hard
          cp -rf ~/html/* .
          git add --all; git commit -m "Docs for ${CURRENT_COMMIT_HASH}"
          git remote add origin-pages https://${GITHUB_PUBLIC_REPO_TOKEN}@$(git config --get remote.origin.url | sed -e "s/^https:\/\///")
          git push --force --set-upstream origin-pages gh-pages
          
    - os: linux
      compiler: gcc
      env: Build & Run Unit Tests
      script:
        - |
          cd workspace
          cmake ../src -DCMAKE_CXX_FLAGS="-pedantic -Wall -Wextra -Ofast -flto -funroll-loops -m64 -march=native"
          make
          ctest --extra-verbose

          cd ..;zip -r ~/ubuntu.zip build -x build/.keep
          
          git remote set-url --push origin https://${GITHUB_PUBLIC_REPO_TOKEN}@$(git config --get remote.origin.url | sed -e "s/^https:\/\///")
          git fetch --all
          git checkout -b gh-pages
          git pull;git clean -fxd;git reset --hard
          mv ~/ubuntu.zip ./build
          git add ./build/ubuntu.zip; git commit -m "Ubuntu build for ${CURRENT_COMMIT_HASH}"
          git push --set-upstream origin gh-pages

    - os: osx
      compiler: clang
      env: Build & Run Unit Tests
      script:
        - |
          cd workspace
          cmake ../src -DCMAKE_CXX_FLAGS="-pedantic -Weverything -Wno-c++98-compat -Ofast -flto -funroll-loops -m64 -march=native"
          make
          ctest --extra-verbose

          #cd ..;zip -r ~/macos.zip build -x build/.keep
          #git checkout -b gh-pages
          #mv ~/macos.zip ./build
          #git add ./build/macos.zip; git commit -m "Macos build for ${CURRENT_COMMIT_HASH}"
          #git remote add origin-pages https://${GITHUB_PUBLIC_REPO_TOKEN}@$(git config --get remote.origin.url | sed -e "s/^https:\/\///")
          #git push --force --set-upstream origin-pages gh-pages
